---
# tasks file for mysql
  - name: install required packages / tools
    apt: name={{ item }} state=present
    with_items:
      - python-mysqldb

  - name: Install mysql package
    apt: name=mysql-server state=present

  - name: ensure mysql listening on all ports
    lineinfile: dest=/etc/mysql/my.cnf regexp=^bind-address line="bind-address = {{ ansible_eth1.ipv4.address }}"
    notify: restart mysql
  
  - name: ensure mysql server started
    service: name=mysql state=started enabled=yes

  - name: create demo database
    mysql_db: name={{ db_name }} state=present

  - name: create database user
    mysql_user: name={{ db_user_name }} password={{ db_user_pass }} priv={{ db_name }}.*:ALL host={{ db_user_host }} state=present

